name: Version Checks

on:
  pull_request:
    branches:
      - main

jobs:
  ensure-new-version:
    runs-on: ubuntu-latest
    steps:
      # set up
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # target versions
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - run: echo "version-name=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
        id: target-version-name

      # source versions
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: echo "version-name=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
        id: source-version-name

      # comparison
      - uses: madhead/semver-utils@latest
        id: compare
        with:
          version: ${{ steps.source-version-name.outputs.version-name }}
          compare-to: ${{ steps.target-version-name.outputs.version-name }}
      - run: '[[ ">" == "${{ steps.compare.outputs.comparison-result }}" ]]'